### ISSUE TITLE
Panic with `No more forward progress made in stream decoding.` on a crafted image

### ISSUE THREAD

**Issue by Shnatsel** [image-rs/image-png#461]
Decoding the following image results in a panic: 
[crash-095de1cef9395bc69ebcb9250ee27b485989f282](https://github.com/image-rs/image-png/assets/291257/dea9ee08-7369-4634-bc4b-5fef33c9a949)

```
thread '<unnamed>' panicked at image-png/src/decoder/zlib.rs:141:17:
No more forward progress made in stream decoding.
```

Found by `cargo fuzz` on commit 5ac3b4189119895f4e47a4391e86e6955855d8e0

Also, after the recent performance optimizations the fuzzer goes absolutely BRRRRRR. I'm getting over 100,000 executions per second per core, I have never seen anything like it :rocket:

**Comment by fintelia** [comment]
This is a bug in `fdeflate` that was fixed in version 0.3.4.

**Comment by fintelia** [comment]
We should probably see about getting you access to the oss-fuzz so you can see crashes detected there. I think it might just be a matter of adding a address gmail [here](https://github.com/google/oss-fuzz/blob/master/projects/image-png/project.yaml)?

**Comment by Shnatsel** [comment]
I can still reproduce this with a different file even on `fdeflate` v0.3.4: [crash-7015e5b72205faf10ae3174f531837d665955b1a](https://github.com/image-rs/image-png/assets/291257/dab9bea2-4ea9-4552-a322-3701e4333a25)

**Comment by fintelia** [comment]
Weirdly, neither file reproduces for me with `fdeflate` v0.3.4

**Comment by Shnatsel** [comment]
Oh, I ran `cargo update` in the root directory but not in the `fuzz` directory. My bad!

**Comment by Shnatsel** [comment]
No more issues after 2.4 billion fuzzer executions :tada:
