### ISSUE TITLE
4-bit grayscale image is read as 8-bit

### ISSUE THREAD

**Issue by kvark** [image-rs/image-png#97]
I'm saving a 4-bit PNG (using this library), and `identify` reports it 4 bit:
```
Image: tmp/meta_low.png
  Format: PNG (Portable Network Graphics)
  Mime type: image/png
  Class: PseudoClass
  Geometry: 2048x16384+0+0
  Units: Undefined
  Colorspace: Gray
  Type: Grayscale
  Base type: Undefined
  Endianess: Undefined
  Depth: 8/4-bit
  Channel depth:
    Gray: 4-bit
  Channel statistics:
    Pixels: 33554432
    Gray:
      min: 0  (0)
      max: 119 (0.466667)
      mean: 24.0818 (0.0944384)
      standard deviation: 22.2654 (0.0873152)
      kurtosis: 7.38533
      skewness: 2.35856
      entropy: 0.627434
```

Not sure what "Depth: 8/4-bit" is, tbh...

When loading, I'm getting `BitDepth::Eight`. Loading code:
```
let file = File::open(path).unwrap();
let decoder = png::Decoder::new(file);
let (info, mut reader) = decoder.read_info().unwrap();
assert_eq!(info.bit_depth, png::BitDepth::Four);
```

**Comment by martinlindhe** [comment]
Looking at this now. We have a 4-bit grayscale png in tests/pngsuite/basn0g04.png with similar properties.

This png has IHDR bit depth value of 0x4, identify says:
```
...
  Colorspace: LinearGray
  Type: Grayscale
...
  Depth: 8/4-bit
  Channel depth:
    Gray: 4-bit
...
```

yet the loading code posted above sets info.bit_depth to png::BitDepth::Eight

**Comment by martinlindhe** [comment]
This is the underlying reason, not sure how to progress. On line 361 bits defaults to 8.

https://github.com/image-rs/image-png/blob/f6fc66d53553075b967cb6dd99c9b1472b9e3fe0/src/decoder/mod.rs#L357-L363

**Comment by fintelia** [comment]
Is the expansion from 4-bits to 8-bits correct? I'm OK not natively supporting 4-bit images as long as we can load them correctly into a format that we can natively support

**Comment by kvark** [comment]
@fintelia I'm interested in both saving and loading as 4-bit, FWIW

**Comment by HeroicKatora** [comment]
I think this was fixed in [`0.15.2`](https://github.com/image-rs/image-png/blob/master/CHANGES.md#0152) and can be closed?

**Comment by kvark** [comment]
Thank you! I'll re-open if I see this again.

**Comment by kvark** [comment]
Looks like this is still happening? I'm on 0.16.7 now.
The code saving PNG is [here](https://github.com/kvark/vange-rs/blob/c22bb8c6fc6ae6df0566f83c2cfafb256d9f2da5/bin/convert/level_png.rs#L51). Relevant is `encoder.set_depth(png::BitDepth::Four);`.
The code loading PNG is [here](https://github.com/kvark/vange-rs/blob/c22bb8c6fc6ae6df0566f83c2cfafb256d9f2da5/bin/convert/level_png.rs#L104), and the assertion fires up:
```
     Running `target/debug/convert tmp/l0.ron tmp/escave.vmp`
	Loading multiple PNGs...
		height.png...
		material_lo.png...
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `Eight`,
 right: `Four`', bin/convert/level_png.rs:106:9
```

**Comment by kvark** [comment]
Ok, so there are 2 issues here that I found:
  1. I was providing the palette of the wrong size (see https://github.com/image-rs/image-png/issues/136#issuecomment-666051256)
  2. the `Decoder` expanded my 4 bits into 8bits RGB by default. I filed #240

Since these issues can be worked around, I'm closing this bug.
